version: "3"
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ./dist:/home/app/dist

    prisma:
        image: prismagraphql/prisma:1.15
        restart: always
        ports:
            - "4466:4466"
        environment:
            PRISMA_CONFIG: |
                port: 4466
                managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
                databases:
                  default:
                    connector: postgres
                    host: postgres
                    port: 5432
                    user: prisma
                    password: prisma
                    migrations: true
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    ? postgres
