version: "3.1"

services:
  db:
    image: postgres:latest
    volumes:
      - hominem-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hominem
    ports:
      - "5432:5432"

volumes:
  hominem-data:
