version: '3.1'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - DB=budgeteer
      - DB_HOST=db
      - DB_DIALECT=sqlite
      - DB_LOGIN=postgres
      - DB_USER=postgres
    ports:
      - "3000:3000"
    secrets:
      - postgres_password

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=budgeteer
    ports:
      - "5432:5432"

secrets:
  postgres_password:
    file: ./secrets/postgres_password