version: "3.1"

services:
  web:
    command: yarn start:dev
    environment:
      DB: budgeteer
      DB_HOST: db
      DB_LOGIN: postgres
      DB_PASSWORD: postgres
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
  db:
    volumes:
      - budgeteer-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budgeteer
    ports:
      - "5432:5432"

volumes:
  budgeteer-data:
