version: '3.1'

services:
  web:
    command: yarn start:dev
    environment:
      DB: budgeteer
      DB_HOST: db
      DB_DIALECT: postgres
      DB_LOGIN: postgres
      DB_USER: postgres
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
  db:
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budgeteer
    ports:
      - "5432:5432"